#!/usr/bin/env python3
"""Generate the case-mapping tables for internal/text/unicode_case_data.mbt.

Sources, both from the UCD (https://www.unicode.org/Public/UCD/latest/ucd/):
UnicodeData.txt fields 13 / 14 — the *simple* mappings, one code point to
one code point — and SpecialCasing.txt — the unconditional full mappings
that differ from the simple ones, the one-to-many expansions (ß -> SS,
the ﬁ ligatures -> FI, İ -> i + combining dot above). Conditional lines
(the locale-specific tail: Turkish and Azerbaijani `i`, Lithuanian and
Final_Sigma contexts) are skipped: the default case conversion carries no
locale.

Together the two tables are the Unicode Standard's default case
conversion — what Rust's `char::to_uppercase` and Polars apply — split so
the one-to-one fast path is a flat sorted array and only the ~100
expanding mappings walk a second small table.

Usage: gen_unicode_case.py <UnicodeData.txt> <SpecialCasing.txt> <out.mbt>
The output is formatted MoonBit; the UCD version is read from
SpecialCasing's header line and recorded in the file header, so the
committed table always names the edition it came from.
"""
import sys

src, special_src, dst = sys.argv[1], sys.argv[2], sys.argv[3]

upper = []  # (cp, mapped) from field 13
lower = []  # (cp, mapped) from field 14
for line in open(src, encoding="utf-8"):
    f = line.split(";")
    cp = int(f[0], 16)
    if f[12]:
        upper.append((cp, int(f[12], 16)))
    if f[13]:
        lower.append((cp, int(f[13], 16)))

def cps(field):
    return [int(t, 16) for t in field.split()]

special_upper = []  # (cp, [mapped...]) where full differs from simple
special_lower = []
for line in open(special_src, encoding="utf-8"):
    code = line.split("#", 1)[0].strip().rstrip(";").strip()
    if not code:
        continue
    f = [p.strip() for p in code.split(";")]
    if len(f) != 4:  # a fifth field is a locale/context condition
        continue
    cp = int(f[0], 16)
    lo, up = cps(f[1]), cps(f[3])
    if len(lo) != 1 or lo[0] != cp:
        special_lower.append((cp, lo))
    if len(up) != 1 or up[0] != cp:
        special_upper.append((cp, up))

# SpecialCasing.txt groups by script, not code point (the FB ligatures sit
# before 0587), and the binary searches need ascending source code points.
special_upper.sort(key=lambda p: p[0])
special_lower.sort(key=lambda p: p[0])

def fmt_simple(pairs):
    return "\n  ".join("(0x%04X, 0x%04X)," % p for p in pairs)

def fmt_special(pairs):
    return "\n  ".join(
        "(0x%04X, [%s])," % (cp, ", ".join("0x%04X" % t for t in to))
        for cp, to in pairs
    )

# The UCD version lives in each source file's header line, e.g.
# "# SpecialCasing-16.0.0.txt", and is carried into the generated header so
# the committed table always names the edition it came from.
import re

ucd_version = None
for line in open(special_src, encoding="utf-8"):
    m = re.search(r"SpecialCasing-(\d+\.\d+\.\d+)\.txt", line)
    if m:
        ucd_version = m.group(1)
        break
assert ucd_version, "no SpecialCasing-<version>.txt header line found"

with open(dst, "w", encoding="utf-8", newline="\n") as w:
    w.write("// Generated by .github/scripts/gen_unicode_case.py from the\n")
    w.write("// Unicode Character Database's UnicodeData.txt and SpecialCasing.txt\n")
    w.write("// (UCD version %s) —\n" % ucd_version)
    w.write("// do not edit by hand; regenerate. The simple tables are fields 13 / 14,\n")
    w.write("// one code point to one code point, sorted by source code point for the\n")
    w.write("// binary searches below. The special tables are SpecialCasing's\n")
    w.write("// unconditional full mappings — where the default case conversion differs\n")
    w.write("// from the simple one, the one-to-many expansions — with the conditional\n")
    w.write("// (locale and context) lines skipped. %d/%d simple, %d/%d special entries.\n" % (
        len(upper), len(lower), len(special_upper), len(special_lower)))
    w.write("\n///|\n")
    w.write("let unicode_simple_upper : Array[(UInt, UInt)] = [\n")
    w.write("  " + fmt_simple(upper) + "\n")
    w.write("]\n")
    w.write("\n///|\n")
    w.write("let unicode_simple_lower : Array[(UInt, UInt)] = [\n")
    w.write("  " + fmt_simple(lower) + "\n")
    w.write("]\n")
    w.write("\n///|\n")
    w.write("let unicode_special_upper : Array[(UInt, Array[UInt])] = [\n")
    w.write("  " + fmt_special(special_upper) + "\n")
    w.write("]\n")
    w.write("\n///|\n")
    w.write("let unicode_special_lower : Array[(UInt, Array[UInt])] = [\n")
    w.write("  " + fmt_special(special_lower) + "\n")
    w.write("]\n")

print("simple upper=%d lower=%d; special upper=%d lower=%d" % (
    len(upper), len(lower), len(special_upper), len(special_lower)))
