#!/usr/bin/env python3
"""Generate the simple case-mapping table for internal/text/unicode_case.mbt.

Source: UnicodeData.txt (https://www.unicode.org/Public/UCD/latest/ucd/),
fields 13 (simple uppercase) and 14 (simple lowercase) — the *simple*
mappings, one code point to one code point, which is what a per-character
case conversion applies. Full (contextual) mappings like "ß" -> "SS" are
deliberately out: a columnar kernel maps each cell one character at a time,
and the Unicode Standard's own default casing for the single-character
spelling ("ß" -> "ẞ", U+1E9E) is what the simple table carries.

Usage: gen_unicode_case.py <UnicodeData.txt> <out.mbt>
The output is formatted MoonBit; commit it with the UCD version it came
from recorded in the file header.
"""
import sys

src, dst = sys.argv[1], sys.argv[2]

upper = []  # (cp, mapped) from field 13
lower = []  # (cp, mapped) from field 14
for line in open(src, encoding="utf-8"):
    f = line.split(";")
    cp = int(f[0], 16)
    if f[12]:
        upper.append((cp, int(f[12], 16)))
    if f[13]:
        lower.append((cp, int(f[13], 16)))

def fmt(pairs):
    out = []
    for cp, m in pairs:
        out.append("(0x%04X, 0x%04X)," % (cp, m))
    return out

body_up = fmt(upper)
body_lo = fmt(lower)

with open(dst, "w", encoding="utf-8", newline="\n") as w:
    w.write("// Generated by .github/scripts/gen_unicode_case.py from the\n")
    w.write("// Unicode Character Database's UnicodeData.txt — do not edit by\n")
    w.write("// hand; regenerate. Fields 13 / 14, the *simple* case mappings: one\n")
    w.write("// code point to one code point, sorted by source code point for the\n")
    w.write("// binary searches below. %d uppercase entries, %d lowercase.\n" % (len(upper), len(lower)))
    w.write("\n///|\n")
    w.write("let unicode_simple_upper : Array[(UInt32, UInt32)] = [\n")
    w.write("  " + " ".join(body_up) + "\n")
    w.write("]\n")
    w.write("\n///|\n")
    w.write("let unicode_simple_lower : Array[(UInt32, UInt32)] = [\n")
    w.write("  " + " ".join(body_lo) + "\n")
    w.write("]\n")

print("upper=%d lower=%d" % (len(upper), len(lower)))
